### ISSUE TITLE
fix sx_regencerts - catch KeyboardInterrupt

### ISSUE THREAD

**Issue by astibal** [astibal/smithproxy#14]
```
Dry certificate check? [Dry/Normal]? ^CTraceback (most recent call last):
  File "/usr/bin/sx_regencerts", line 309, in <module>
    if ask_bot(['Dry','Normal'], "Dry certificate check?") == 'Dry':
  File "/usr/share/smithproxy/infra/bend/bendutil.py", line 138, in ask_bot
    response = input(ask_question)
KeyboardInterrupt
```

**Comment by astibal** [comment]
Fixed with improvements in 3ec99307103645572057d959750065d31c7d0ea3
